// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1746110344);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1746122103);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1746109634);
user_pref("app.update.lastUpdateTime.region-update-timer", 1746110344);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1746110344);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1746110375);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1746110344);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{a986c9a7-f8d8-4465-9281-90a4227cdac6}");
user_pref("browser.download.lastDir", "/home/matvey/Загрузки");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1746109630);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 148);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5af998f0-4f9e-4a02-8835-044193431229}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1746109632);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1746122068576");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1746123844576");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1746110316335");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1746131916335");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250421121556");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1746123696");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20250421121556");
user_pref("browser.startup.homepage_override.mstone", "128.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1746123696);
user_pref("browser.startup.page", 3);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.topsites.contile.lastFetch", 1746123697);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"simple-translate_sienori-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\",\"ublock0_raymondhill_net-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"simple-translate_sienori-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\",\"unified-extensions-area\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1746109633478");
user_pref("devtools.everOpened", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "128.10.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "RU");
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("doh-rollout.uri", "https://mozilla.cloudflare-dns.com/dns-query");
user_pref("dom.push.userAgentID", "623e41f42c32476aa203feaca986d937");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECBGgXgvtuT2+BAjlqlithvLYDQ==");
user_pref("extensions.getAddons.cache.lastUpdate", 1746123697);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250421121556");
user_pref("extensions.lastAppVersion", "128.10.0");
user_pref("extensions.lastPlatformVersion", "128.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.quarantinedDomains.list", "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.plugin.hidden", false);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.simple-translate@sienori", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"78cb1100-9f7b-4c53-a666-b10d2e6fb5b4\",\"pictureinpicture@mozilla.org\":\"04a8e874-b515-4680-9915-055d3f2feb0a\",\"screenshots@mozilla.org\":\"e3c367dc-9d2e-44f6-8f34-0859aeba1068\",\"webcompat-reporter@mozilla.org\":\"ba81e3f2-2f5c-4487-b9f5-f32b7641b3ea\",\"webcompat@mozilla.org\":\"bf1d68fd-78b7-4d04-9ce6-f0c88c1701af\",\"default-theme@mozilla.org\":\"275f4c0a-bef2-4fba-ad29-bacd6743f499\",\"addons-search-detection@mozilla.com\":\"2957fdfc-6c93-4f16-a859-5a55d2364cb4\",\"firefox-compact-dark@mozilla.org\":\"cce57f8e-2c37-4d07-ae8c-06c78c57a736\",\"uBlock0@raymondhill.net\":\"9be8c44c-bd07-4ba7-a6b4-ce8ac2a8c220\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"b41679ed-0cf7-469b-9376-896a7473996e\",\"simple-translate@sienori\":\"50422eba-3b80-4a0d-ac48-35d634bb7bbc\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1746111301);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "f5246bf14d038adf4ce0c4360262ab722bc3de4220f047c3d542b4c564074b4877dc8659e3125c5171c749e7ce93f20cc63777eb5e1539e960670cbc5f30ac85");
user_pref("media.gmp-gmpopenh264.lastDownload", 1746110344);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1746110344);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1746110344);
user_pref("media.gmp-gmpopenh264.version", "2.6.0");
user_pref("media.gmp-manager.buildID", "20250421121556");
user_pref("media.gmp-manager.lastCheck", 1746110660);
user_pref("media.gmp-manager.lastEmptyCheck", 1746110660);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.videocontrols.picture-in-picture.video-toggle.first-seen-secs", 1746117616);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1746111301);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1746111301026");
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "7ec4ed67-6e8f-4a42-82e3-01603dfc577d");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1746122738);
user_pref("services.settings.blocklists.gfx.last_check", 1746122738);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1746122458970\"");
user_pref("services.settings.last_update_seconds", 1746122738);
user_pref("services.settings.main.addons-manager-settings.last_check", 1746122738);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1746122738);
user_pref("services.settings.main.cfr.last_check", 1746122738);
user_pref("services.settings.main.cookie-banner-rules-list.last_check", 1746122738);
user_pref("services.settings.main.devtools-compatibility-browsers.last_check", 1746122738);
user_pref("services.settings.main.devtools-devices.last_check", 1746122738);
user_pref("services.settings.main.doh-config.last_check", 1746122738);
user_pref("services.settings.main.doh-providers.last_check", 1746122738);
user_pref("services.settings.main.fingerprinting-protection-overrides.last_check", 1746122738);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1746122738);
user_pref("services.settings.main.hijack-blocklists.last_check", 1746122738);
user_pref("services.settings.main.language-dictionaries.last_check", 1746122738);
user_pref("services.settings.main.message-groups.last_check", 1746122738);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1746122738);
user_pref("services.settings.main.partitioning-exempt-urls.last_check", 1746122738);
user_pref("services.settings.main.password-recipes.last_check", 1746122738);
user_pref("services.settings.main.password-rules.last_check", 1746122738);
user_pref("services.settings.main.pioneer-study-addons-v1.last_check", 1746122738);
user_pref("services.settings.main.public-suffix-list.last_check", 1746122738);
user_pref("services.settings.main.query-stripping.last_check", 1746122738);
user_pref("services.settings.main.search-config-icons.last_check", 1746122738);
user_pref("services.settings.main.search-config-overrides-v2.last_check", 1746122738);
user_pref("services.settings.main.search-config-overrides.last_check", 1746122738);
user_pref("services.settings.main.search-config-v2.last_check", 1746122738);
user_pref("services.settings.main.search-config.last_check", 1746122738);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1746122738);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1746122738);
user_pref("services.settings.main.sites-classification.last_check", 1746122738);
user_pref("services.settings.main.tippytop.last_check", 1746122738);
user_pref("services.settings.main.top-sites.last_check", 1746122738);
user_pref("services.settings.main.translations-models.last_check", 1746122738);
user_pref("services.settings.main.translations-wasm.last_check", 1746122738);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1746122738);
user_pref("services.settings.main.websites-with-shared-credential-backends.last_check", 1746122738);
user_pref("services.settings.security-state.cert-revocations.last_check", 1746122738);
user_pref("services.settings.security-state.intermediates.last_check", 1746122738);
user_pref("services.settings.security-state.onecrl.last_check", 1746122738);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECO2lfi7wULcXBAiOmOphn5opFA==");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1746111301);
user_pref("toolkit.startup.last_success", 1746123695);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20250421121556");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);


//Тонкие вкладки и поисковая строка
user_pref("browser.uidensity", 1);

// Отключаем Pocket
user_pref("extensions.pocket.api", "");
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.site", "");
user_pref("extensions.pocket.oAuthConsumerKey", "");

//Отключаем анимацию открытия видео на фуллскин и подсказку "нажмите esc.."
user_pref("full-screen-api.transition-duration.enter", "0");
user_pref("full-screen-api.transition-duration.leave", "0");
user_pref("full-screen-api.warning.timeout", 0);

//Просим сайты не отслеживать Вас
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.donottrackheader.enabled", true);

//Отключаем телеметрию и отправку отчетов
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.cachedClientID", "");
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.hybridContent.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.previousBuildID", "");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.server_owner", "");
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("datareporting.healthreport.infoURL", "");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.firstRunURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.tabs.crashReporting.email", false);
user_pref("browser.tabs.crashReporting.emailMe", false);
user_pref("breakpad.reportURL", "");
user_pref("security.ssl.errorReporting.automatic", false);
user_pref("toolkit.crashreporter.infoURL", "");
user_pref("network.allow-experiments", false);
user_pref("dom.ipc.plugins.reportCrashURL", false);
user_pref("dom.ipc.plugins.flash.subprocess.crashreporter.enabled", false);

